version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    volumes:
      - $HOME/data/:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    hostname: localhost
    network_mode: host

  consumer-service:
    build: ./Rabbit-Mq-Consumer/.
    container_name: rabbitmq-consumer
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
    restart: always
    expose:
      - 8081
    hostname: localhost
    network_mode: host

  producer-service:
    build: ./Rabbit-Mq-Producer/.
    container_name: rabbitmq-producer
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    restart: always
    expose:
      - 8080
    hostname: localhost
    network_mode: host